### ISSUE TITLE
mocha のテスト外で power-assert を読み込んでも反映されない

### ISSUE THREAD

**Issue by kjirou** [kjirou/si_of_sis#134]
`helper/test` 内で `power-assert` を読み込んだメソッドを作ったら、標準 assert と同じ出力になっていた。

`'espower-coffee/guess'` をモジュール内で読んでもダメだった。
とりあえずは `power-assert` 本体とどっちの問題か仕様なのかを調べる。

**Comment by twada** [comment]
power-assert 化するためのツール達は
1. ファイルパターンにマッチしたファイルの中の
2. アサーションパターンにマッチしたアサーション呼び出し

を編集します。 `espower-coffee/guess` の場合、ファイルパターンは `test/**/*.coffee` で、アサーションパターンは

```
[
    'assert(value, [message])',
    'assert.ok(value, [message])',
    'assert.equal(actual, expected, [message])',
    'assert.notEqual(actual, expected, [message])',
    'assert.strictEqual(actual, expected, [message])',
    'assert.notStrictEqual(actual, expected, [message])',
    'assert.deepEqual(actual, expected, [message])',
    'assert.notDeepEqual(actual, expected, [message])'
]
```

です。これをカスタマイズするには[外部ファイルを作成します](https://github.com/twada/espower-coffee#more-customization)

今回の場合は対象ファイルが `helpers/test.coffee` なので、ファイルパターンにマッチしなかったのかなと思います。ファイルパターンには[minimatch の記法](http://motemen.hatenablog.com/entry/2014/07/15/minimatch-cheat-sheet)を使います。

ということで、外部設定ファイルでファイルパターンだけ上書きして

``` javascript
require('espower-coffee')({
    pattern: '{test,helper}/**/*.coffee'
});
```

そのファイルを `espower-coffee/guess` の代わりに  mocha.opts の中で `--require` すれば、動くのではないかなと思います。

**Comment by kjirou** [comment]
@twada ありがとうございます..!

![](http://cdn-ak.f.st-hatena.com/images/fotolife/g/gotocc/20101123/20101123074729.jpg)

**Comment by twada** [comment]
:+1:

**Comment by twada** [comment]
README に FAQ や TROUBLE SHOOTING みたいなセクションを作ろうと思います。ありがとうございます。

**Comment by kjirou** [comment]
@twada ありがとうございます！
ただこの点、自分が README を一読すらしなかったのが問題だったと思っています。

https://github.com/twada/espower-coffee#more-customization
↑ どう見ても書いてあるし、英語力がなくても読み易い

ぶっちゃけ、このレベルの疑問（自分で言うのもなんですが）を README 内で拾うのも大変そうなので、誰かが書いてくれる日本語のブログ記事など、そういうのに任せてもいいのでは思いました。

とりあえず、後で自分も記事にしておこうと思います。

---

また、別件なのですが質問が一点あります。

> ということで、外部設定ファイルでファイルパターンだけ上書きして

現実装ですと、設定のカスタマイズをする場合は `options.cwd` と `options.pattern` の両方の明示指定が必要だったのですが、これは現実装が仕様としても正しいという解釈でOKでしょうか。
（README の内容も「明示的に指定して」となっていますし）

初期値対応する場合は `guess.js` との共通化が必要になりそうなので、その辺で今の実装になっているのかな？と思ったりしました。
なお、自分としては、設定項目も多くないですし、現実装がベターだと感じています。

**Comment by twada** [comment]
> 現実装ですと、設定のカスタマイズをする場合は options.cwd と options.pattern の両方の明示指定が必要だったのですが、これは現実装が仕様としても正しいという解釈でOKでしょうか。
> （README の内容も「明示的に指定して」となっていますし）

そのとおりです……!

明示的に設定する際は `process.cwd()` をデフォルト値として使うのを避けようかなと考えていたことを忘れていました。

ですので、現時点の実装 == 仕様で問題ありません。私の issue コメントに不正確さがあったということです……すみませんでした。

**Comment by kjirou** [comment]
:smiley:
